[project]
name = "cnfunds-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "pytest>=8.3.4",
    "requests>=2.32.3",
    "tenacity>=9.0.0",
    "tqdm>=4.67.1",
    "typer>=0.15.1",
]
